### ISSUE TITLE
Please add a license file and explain what it does in the readme

### ISSUE THREAD

**Issue by unixorn** [Taimoor-Tariq/zsh-supabase#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Also, it's unclear exactly what it does - please add an explanation in the readme.

Thanks!

**Comment by Taimoor-Tariq** [comment]
Done
